### ISSUE TITLE
Roadmap: recipes support for sparse tibbles

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/recipes#1343]
This issue is purely based on the integration part of using sparse tibbles in recipes as input/output. A different roadmap issue will be posted about having individual steps produce sparse columns.

What we need:

- [x] `recipe()` to take sparse tibbles as data https://github.com/tidymodels/recipes/pull/1364
- [x] `recipe()` to take {Matrix} sparse matrix as data https://github.com/tidymodels/recipes/pull/1367
  - turn them into sparse tibbles early
- [x] `prep()` to take sparse tibbles as data https://github.com/tidymodels/recipes/pull/1366
- [x] `prep()` to take {Matrix} sparse matrix as data https://github.com/tidymodels/recipes/pull/1368
  - turn them into sparse tibbles early
- [x] `bake()` to take sparse tibbles as data https://github.com/tidymodels/recipes/pull/1366
- [x] `bake()` to take {Matrix} sparse matrix as data https://github.com/tidymodels/recipes/pull/1369
  - turn them into sparse tibbles early
- [x] Document how sparse tibbles work within a recipe https://github.com/tidymodels/recipes/pull/1370
  - not all transformations are sparse safe

Adding all of this will give us
- standalone usage of sparse matrices in {recipes} 
- everything it needs to be able to work with the rest of {tidymodels} in regards to sparse tibbles
