### ISSUE TITLE
0.0.4 checklist

### ISSUE THREAD

**Issue by topepo** [tidymodels/recipes#258]
Prepare for release:

* [x] `devtools::check_win_devel()`
* [x] `rhub::check_for_cran()`
* [x] `revdepcheck::revdep_check(num_workers = 4)`
* [x] [Polish NEWS](http://style.tidyverse.org/news.html#before-release)
* [x] If new failures, update `email.yml` then `revdepcheck::revdep_email_maintainers()`

Perform release:

* [x] Create RC branch (for bigger releases)
* [x] Bump version (in DESCRIPTION and NEWS)
* [x] `devtools::check_win_devel()` (again!)
* [x] `devtools::submit_cran()`
* [x] Approve email

Wait for CRAN...

* [x] Tag release
* [x] Merge RC back to master branch
* [x] `pkgdown::build_site()`
* [x] Bump dev version
*  ~Write blog post~ Deferred for a `tidymodels` general update. 

Template from <https://github.com/r-lib/usethis/issues/338>

**Comment by topepo** [comment]
@aravindhebbali @brian-j-smith @EmilHvitfeldt @michaellevy @smaakage85

I've sent the new version of recipes off to CRAN and will update this thread when I know more. 

If you need to test against it, you can remove remotes when you send it to win-builder; any devel package submitted there in the last few weeks is available as a local dependency.

**Comment by topepo** [comment]
On CRAN now.
